#pragma config(Sensor, dgtl7,  bars,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  intake,         sensorDigitalOut)
#pragma config(Motor,  port1,           rfDriveMot,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rbLiftMot,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           tLiftMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bLiftMot,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lbLiftMot,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rbDriveMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lbDriveMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lfDriveMot,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lPowerReq;
int rPowerReq;
int liftStillSpeed;
enum barPos {drop, down};
int barVal[] = {1, 0};
//#region drive functions
void setLMotors(int power)
{
	motor[lfDriveMot] = power;
	motor[lbDriveMot] = power;
}
void setRMotors(int power)
{
	motor[rfDriveMot] = power;
	motor[rbDriveMot] = power;
}
//#endregion
//#region lift functions
void setLiftMotors(int power)
{
	motor[tLiftMot] = power;
	motor[rbLiftMot] = power;
	motor[lbLiftMot] = power;
}
//#endregion
void barRequest(barPos bar)
{
	SensorValue[bars]=bar;
}

task main()
{
	while(1==1)
	{
				/*if(vexRT[Ch3] <= 5 && vexRT[Ch3] >= -5){
				lPowerReq = vexRT[Ch3Xmtr2];}
			else{
				lPowerReq = vexRT[Ch3];}

			if(vexRT[Ch2] <= 5 && vexRT[Ch2] >= -5){
				rPowerReq = vexRT[Ch2Xmtr2];}
			else{
				rPowerReq = vexRT[Ch2];}*/
				motor[lfDriveMot] = vexRT[Ch3];
				motor[lbDriveMot] = vexRT[Ch3];
				motor[rfDriveMot] = vexRT[Ch2];
				motor[rbDriveMot] = vexRT[Ch2];
	//<editor-fold lift
	      if(vexRT[Btn5U] == 1){
					motor[tLiftMot] = 127;
					motor[bLiftMot] = 127;

					liftStillSpeed=15;}
	      else if(vexRT[Btn5D] == 1){
					motor[tLiftMot] = -127;
					motor[bLiftMot] = -127;
					liftStillSpeed=-15;}
	      else{
					motor[tLiftMot] = liftStillSpeed;
					motor[bLiftMot] = liftStillSpeed;
	      //</editor-fold>

	      //<editor-fold intake
	      if(vexRT[Btn6U] == 1){
	      SensorValue[intake]=1;}
				else if(vexRT[Btn6D] == 1){
	      SensorValue[intake]=0;}
	      else if(vexRT[Btn8RXmtr2] == 1){
	      SensorValue[intake]=1;}
	      else if(vexRT[Btn8DXmtr2] == 1){
	      SensorValue[intake]=0;}
	      //</editor-fold>

	      //<editor-fold bar
	      	if(vexRT[Btn8D] == 1){
	   	    //setBarMotors(127);
	     		SensorValue[bar]=0;}
					else if(vexRT[Btn8R] == 1){
	   	    //setBarMotors(-127);
					SensorValue[bar]=1;}

	     	 	/*else
	     	 		setBarMotors(lastBarBtnPressed == 1 ? barStillUp : barStillDown);*/
	      //</editor-fold>
	      //<editor-fold goal
	      if(vexRT[Btn7U] == 1){
	        motor[lgoalMot] =127;
					motor[rgoalMot] =127 ;}
	    	else if(vexRT[Btn7D] == 1){
	        motor[lgoalMot] =-127;
					motor[rgoalMot] =-127 ;}
	      else{
	      	motor[lgoalMot] =vexRT[Ch3] ;
					motor[rgoalMot] =vexRT[Ch2] ;}
	      //</editor-fold>

	}




}
