#pragma config(Motor,  port1,           rfDriveMot,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           intakeMot,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fourBarMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           tLiftMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bLiftMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rgoalMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lgoalMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rbDriveMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lbDriveMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lfDriveMot,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int barRunSpeed;
int lPowerReq;
int rPowerReq;
int barflip;
int barstop;
int liftStillSpeed;
int barStillSpeed;
task main()
{
	while(1==1)
	{
		if(vexRT[Ch3] <= 5 && vexRT[Ch3] >= -5)
			lPowerReq = (vexRT[Ch3Xmtr2]/1.5);
		else
			lPowerReq = vexRT[Ch3];

		if(vexRT[Ch2] <= 5 && vexRT[Ch2] >= -5)
			rPowerReq = (vexRT[Ch2Xmtr2]/1.5);
		else
			rPowerReq = vexRT[Ch2];

    motor[lfDriveMot] = lPowerReq;
    motor[lbDriveMot] = lPowerReq;
    motor[rfDriveMot] = rPowerReq;
    motor[rbDriveMot] = rPowerReq;



    if(vexRT[Btn5U] == 1){
      motor[tLiftMot] = 127;
      motor[bLiftMot] = 127;

      liftStillSpeed=15;}
    else if(vexRT[Btn5D] == 1){
      motor[tLiftMot] = -127;
      motor[bLiftMot] = -127;
      liftStillSpeed=-15;}
    else{
      motor[tLiftMot] = liftStillSpeed;
      motor[bLiftMot] = liftStillSpeed;}

      if(vexRT[Btn7U] == 1){
        motor[lgoalMot] =127;
        motor[rgoalMot] =127 ;}
      else if(vexRT[Btn7D] == 1){
        motor[lgoalMot] =-127;
        motor[rgoalMot] =-127 ;}
      else{
        motor[lgoalMot] =lPowerReq ;
        motor[rgoalMot] =rPowerReq ;}

        /*if(vexRT[Btn8D] == 1){
        //setBarMotors(127);
        SensorValue[bars]=0;}
        else if(vexRT[Btn8R] == 1){
        //setBarMotors(-127);
        SensorValue[bars]=1;}*/

     if(vexRT[Btn6U] == 1){
     	 motor[intakeMot] = -127;}
   	 else if(vexRT[Btn6D] == 1){
      	motor[intakeMot] = 127;}
     else{
      	motor[intakeMot] = -20;}

      if (vexRT[Btn6U] == 0)
      	{
      		barstop = 0;

      	}
      if(vexRT[Btn8R] == 1 && barstop == 0)
      	{
      		barstop = 1;
      		barflip = 1;
      		barRunSpeed = -127;
      		barStillSpeed = -15;
      		time1[T1]=0;
      		wait1Msec(20);
      	}
      else if(vexRT[Btn8D] == 1 && barstop == 0)
      	{
      		barstop = 1;
      		barflip = 0;
      		barRunSpeed = 127;
      		barStillSpeed = 15;
      		time1[T1]=0;
      		wait1Msec(20);
      	}
      else if(time1[T1]<600)
      	{
      		motor[fourBarMot]=barRunSpeed;
      	}
      else
      	{
      		motor[fourBarMot]=barStillSpeed;
    		}

  }
}
