#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    GoalPot,        sensorPotentiometer)
#pragma config(Sensor, in4,    barPot,         sensorPotentiometer)
#pragma config(Sensor, in5,    cancer,         sensorLineFollower)
#pragma config(Sensor, in6,    lPot,           sensorPotentiometer)
#pragma config(Sensor, in7,    rPot,           sensorPotentiometer)
#pragma config(Sensor, dgtl3,  rEnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  lEnc,           sensorQuadEncoder)
#pragma config(Motor,  port1,           rtLiftMot,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           intakeMot,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           barMot,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rDriveMot,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bLiftMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rGoalMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lGoalMot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ltLiftMot,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lbDriveMot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lfDriveMot,    tmotorVex393_HBridge, openLoop)
